# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-20 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerName', models.CharField(max_length=200)),
                ('providerEmail', models.CharField(max_length=100)),
                ('providerNo', models.CharField(max_length=50)),
                ('providerLanguage', models.CharField(max_length=50)),
                ('providerCurrency', models.CharField(max_length=50)),
            ],
        ),
    ]
