# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-20 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='providers',
            table='providers',
        ),
    ]
