# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20180820_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('geometry', models.TextField(default='')),
                ('forProviderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.providers')),
            ],
        ),
    ]
